### ISSUE TITLE
SUMMARY: Meets Expectations

### ISSUE THREAD

**Issue by jzhu01** [MCloud2/prj-rev-bwfs-tea-cozy#5]
Stellar job on this project - I really liked how you styled the nav, as well as how you chose to set up your copyright. In terms of improvement, I recommend adding an opacity to the images and setting a width on your tea-of-the-month section. 

If you’re in the mood for a challenge, I would look into implementing a mobile version of this page! Here's a link to get you started: https://www.w3schools.com/css/css_rwd_mediaqueries.asp. Keep up the awesome work! ^_^

**Comment by MCloud2** [comment]
Thanks for the feedback! It's been very helpful.

Somehow setting a width on the tea-of-the-month section just never occurred to me (probably because I was using a rather narrow screen throughout most of the testing). I realize now I probably should have thought to test it on a wider one as well. Thanks for bringing it to my attention. :)
